version: "3.7"
services:
  api:
    image: golang:latest
    environment:
      - DIMENSION=46
      - ASSETS_PATH=assets/default
      - LIGHT_SQUARE_RGB=209,139,71
      - DARK_SQUARE_RGB=255,206,158
    volumes:
      - .:/go/src/go-fen
    ports:
      - 8080:8080
    working_dir: /go/src/go-fen/src
    command: go run main.go
