#!/bin/bash
docker build . \
    -t $IMAGE_NAME \
    --build-arg DIMENSION=60 \
    --build-arg ASSETS_PATH=assets/standardx60 \
    --build-arg LIGHT_SQUARE_RGB=209,139,71 \
    --build-arg DARK_SQUARE_RGB=255,206,158 \
